import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from './navBar';
import { TripProvider } from "./trip/TripContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TripProvider>
            <header>
            <NavBar />  
          </header>

          {/* Background for main page */}

          <main className="min-h-screen bg-cover bg-center" style={{ backgroundImage: "url('/Airplane_Background.jpg')"}}>
            {children}
            
          </main>

          <footer>

            <img src="/facebook.png" alt="facebook" id="facebook" style={{display: 'inline-block', marginRight: '10px'}} />
            <img src="/twitterlogo.png" alt="twitter" id="twitter" style={{display: 'inline-block', marginRight: '10px'}} />
            <img src="/instagramlogo.png" alt="instagram" id="instagram" style={{display: 'inline-block', marginRight: '10px'}} />
            <a href="/contact" id="contactUs" style={{display: 'inline-block', marginRight: '10px'}}>Contact Us!</a>
            <div className="footer-bottom"> <p>© 2025 JetSetGo. All Rights Reserved.</p></div>
          
          </footer>
        </TripProvider>
      </body>
    </html>
  );
}
